export const POSTING_FETCH_REQUEST = 'POSTING/POSTING_FETCH_REQUEST'
export const POSTING_FETCH_SUCCESS = 'POSTING/POSTING_FETCH_SUCCESS'
export const POSTING_FETCH_FAILURE = 'POSTING/POSTING_FETCH_FAILURE'



