
export const POSTINGS_FETCH_REQUEST = 'APP/POSTINGS_FETCH_REQUEST';
export const POSTINGS_FETCH_SUCCESS = 'APP/POSTINGS_FETCH_SUCCESS';
export const POSTINGS_FETCH_FAILURE = 'APP/POSTINGS_FETCH_FAILURE';